version: '2'
services:
    soundxtream3-app:
        image: soundxtream3
        external_links:
            - soundxtream3-mysql:mysql
            - soundxtream3-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/soundxtream3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    soundxtream3-mysql:
        extends:
            file: mysql.yml
            service: soundxtream3-mysql
    soundxtream3-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: soundxtream3-elasticsearch
